title: Juan Sebastián Cañas
logo: IMG_0663.jpg
description: ¡Hola! I'm an applied mathematician passionate about artificial intelligence for social impact and sustainability. My long-term goal is to learn, understand, and construct computational models against the global ecological crisis.
theme: jekyll-theme-minimal
