title: Juan Sebastian Cañas
logo: IMG_0663.jpg
description: ¡Hola! I'm an applied mathematician passionate about artificial intelligence for social impact and sustainability. My long-term goal is to learn, understand, and construct computational models to solve real-world problems in socio-ecological systems, biodiversity conservation, and climate change.
theme: jekyll-theme-minimal
